### ISSUE TITLE
Question Regarding PRs

### ISSUE THREAD

**Issue by peasant98** [dpkoch/imu_calib#1]
Hello @dpkoch,

I was wondering if this repo is currently being maintained, so that my colleagues and I (in a research lab) could make a PR. Thanks!

**Comment by dpkoch** [comment]
Hi @peasant98, sorry for the delay.

I'm not really actively maintaining this repo anymore (probably obvious from my response time). If you did want to make a PR I'd be happy to take a look at it, depending on how big of a change it is. If you'd rather just continue working out of your own fork, then that's great too. Either way, thanks for reaching out!

**Comment by peasant98** [comment]
Hi @dpkoch, we ended up finding a bug in our own code -- once we fixed it, everything went well. Closing this issue now.
